### ISSUE TITLE
This feature requires ASM6

### ISSUE THREAD

**Issue by TOPWN** [niuxiaowei/ReplaceMethod#2]
Android gradle 版本号： classpath 'com.android.tools.build:gradle:4.0.0'
编译报错 "This feature requires ASM6"

**Comment by niuxiaowei** [comment]
使用最新库

**Comment by zhaiyunbin** [comment]
1.0.3 还是有这个问题

**Comment by zhaiyunbin** [comment]
> 

1.0.3 还是有这个问题
